//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamCong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMPLOYEEEntities1 : DbContext
    {
        public EMPLOYEEEntities1()
            : base("name=EMPLOYEEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblBANGCONG> tblBANGCONGs { get; set; }
        public virtual DbSet<tblCHUCVU> tblCHUCVUs { get; set; }
        public virtual DbSet<tblHOPDONG> tblHOPDONGs { get; set; }
        public virtual DbSet<tblKHENTHUONG> tblKHENTHUONGs { get; set; }
        public virtual DbSet<tblKILUAT> tblKILUATs { get; set; }
        public virtual DbSet<tblLOAICA> tblLOAICAs { get; set; }
        public virtual DbSet<tblLOAICONG> tblLOAICONGs { get; set; }
        public virtual DbSet<tblLUONG> tblLUONGs { get; set; }
        public virtual DbSet<tblNGHIPHEP> tblNGHIPHEPs { get; set; }
        public virtual DbSet<tblNHANVIEN> tblNHANVIENs { get; set; }
        public virtual DbSet<tblNHANVIEN_PHUCAP> tblNHANVIEN_PHUCAP { get; set; }
        public virtual DbSet<tblPHONGBAN> tblPHONGBANs { get; set; }
        public virtual DbSet<tblPHUCAP> tblPHUCAPs { get; set; }
        public virtual DbSet<tblQUYEN> tblQUYENs { get; set; }
        public virtual DbSet<tblQUYENNV> tblQUYENNVs { get; set; }
        public virtual DbSet<tblTANGCA> tblTANGCAs { get; set; }
        public virtual DbSet<tblTKNV> tblTKNVs { get; set; }
        public virtual DbSet<tblTRINHDO> tblTRINHDOes { get; set; }
        public virtual DbSet<tblUNGLUONG> tblUNGLUONGs { get; set; }
        public virtual DbSet<tblBAOHIEM> tblBAOHIEMs { get; set; }
        public virtual DbSet<tblBAOCAONHANVIEN> tblBAOCAONHANVIENs { get; set; }
    }
}
