//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamCong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBANGCONG
    {
        public long ID_BANGCONG { get; set; }
        public Nullable<System.DateTime> GIOVAO { get; set; }
        public Nullable<System.DateTime> GIORA { get; set; }
        public Nullable<long> ID_LOAICONG { get; set; }
        public Nullable<long> ID_NHANVIEN { get; set; }
        public Nullable<long> CREATE_BY { get; set; }
        public Nullable<long> UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<System.DateTime> NGAYCONGHIENTAI { get; set; }
    
        public virtual tblLOAICONG tblLOAICONG { get; set; }
        public virtual tblNHANVIEN tblNHANVIEN { get; set; }
    }
}
